name: Deploy to EC2

on:
  push:
    branches:
      - pruebas4

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission to Gradle
        run: chmod +x ./gradlew

      - name: Build JAR
        run: ./gradlew build -x test

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "build/libs/ktor-sample-all.jar"
          target: "/home/ubuntu/app/"
          overwrite: true

      - name: Restart Ktor service
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Stopping old service..."
            sudo systemctl stop ktor || true

            echo "Updating permissions..."
            sudo chmod 755 /home/ubuntu/app/ktor-sample-all.jar

            echo "Starting service..."
            sudo systemctl start ktor

            echo "Checking service status..."
            sudo systemctl status ktor --no-pager

            echo "Last logs:"
            sudo journalctl -u ktor -n 20 --no-pager
